################################################################################
# Automatically-generated file. Do not edit!
################################################################################

OBJ_SRCS := 
ASM_SRCS := 
C_SRCS := 
O_SRCS := 
S_UPPER_SRCS := 
EXECUTABLES := 
OBJS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
build/app_trace \
build/app_trace/gcov \
build/app_update \
build/asio/asio/asio/src \
build/bootloader/bootloader_support/src \
build/bootloader/bootloader_support/src/esp32 \
build/bootloader/efuse/esp32 \
build/bootloader/efuse/src/esp32 \
build/bootloader/efuse/src \
build/bootloader/log \
build/bootloader/main \
build/bootloader/micro-ecc/micro-ecc \
build/bootloader/soc/esp32 \
build/bootloader/soc/src/hal \
build/bootloader/soc/src \
build/bootloader/spi_flash/esp32 \
build/bootloader_support/src \
build/bootloader_support/src/idf \
build/bt/common/btc/core \
build/bt/common/osi \
build/bt/controller \
build/bt/host/bluedroid/api \
build/bt/host/bluedroid/bta/ar \
build/bt/host/bluedroid/bta/av \
build/bt/host/bluedroid/bta/dm \
build/bt/host/bluedroid/bta/gatt \
build/bt/host/bluedroid/bta/hf_ag \
build/bt/host/bluedroid/bta/hf_client \
build/bt/host/bluedroid/bta/hh \
build/bt/host/bluedroid/bta/jv \
build/bt/host/bluedroid/bta/sdp \
build/bt/host/bluedroid/bta/sys \
build/bt/host/bluedroid/btc/core \
build/bt/host/bluedroid/btc/profile/esp/blufi \
build/bt/host/bluedroid/btc/profile/std/a2dp \
build/bt/host/bluedroid/btc/profile/std/avrc \
build/bt/host/bluedroid/btc/profile/std/gap \
build/bt/host/bluedroid/btc/profile/std/gatt \
build/bt/host/bluedroid/btc/profile/std/hf_ag \
build/bt/host/bluedroid/btc/profile/std/hf_client \
build/bt/host/bluedroid/btc/profile/std/spp \
build/bt/host/bluedroid/device \
build/bt/host/bluedroid/external/sbc/decoder/srce \
build/bt/host/bluedroid/external/sbc/encoder/srce \
build/bt/host/bluedroid/external/sbc/plc \
build/bt/host/bluedroid/hci \
build/bt/host/bluedroid/main \
build/bt/host/bluedroid/stack/a2dp \
build/bt/host/bluedroid/stack/avct \
build/bt/host/bluedroid/stack/avdt \
build/bt/host/bluedroid/stack/avrc \
build/bt/host/bluedroid/stack/btm \
build/bt/host/bluedroid/stack/btu \
build/bt/host/bluedroid/stack/gap \
build/bt/host/bluedroid/stack/gatt \
build/bt/host/bluedroid/stack/hcic \
build/bt/host/bluedroid/stack/l2cap \
build/bt/host/bluedroid/stack/rfcomm \
build/bt/host/bluedroid/stack/sdp \
build/bt/host/bluedroid/stack/smp \
build/cbor/tinycbor/src \
build/coap/libcoap/src \
build/coap/port \
build/console/argtable3 \
build/console \
build/console/linenoise \
build/cxx \
build/driver \
build/efuse/esp32 \
build/efuse/src/esp32 \
build/efuse/src \
build/esp-tls \
build/esp32 \
build/esp_adc_cal \
build/esp_common/src \
build/esp_eth/src \
build/esp_event \
build/esp_gdbstub/esp32 \
build/esp_gdbstub/src \
build/esp_gdbstub/xtensa \
build/esp_http_client \
build/esp_http_client/lib \
build/esp_http_server/src \
build/esp_http_server/src/util \
build/esp_https_ota/src \
build/esp_local_ctrl/proto-c \
build/esp_local_ctrl/src \
build/esp_netif \
build/esp_netif/loopback \
build/esp_netif/lwip \
build/esp_ringbuf \
build/esp_rom \
build/esp_websocket_client \
build/esp_wifi/src \
build/espcoredump/src \
build/expat/expat/expat/lib \
build/fatfs/diskio \
build/fatfs/port/freertos \
build/fatfs/src \
build/fatfs/vfs \
build/freemodbus/common \
build/freemodbus/modbus/ascii \
build/freemodbus/modbus/functions \
build/freemodbus/modbus \
build/freemodbus/modbus/rtu \
build/freemodbus/modbus/tcp \
build/freemodbus/port \
build/freemodbus/serial_master/modbus_controller \
build/freemodbus/serial_slave/modbus_controller \
build/freertos \
build/heap \
build/jsmn/src \
build/json/cJSON \
build/libsodium/libsodium/src/libsodium/crypto_aead/chacha20poly1305/sodium \
build/libsodium/libsodium/src/libsodium/crypto_aead/xchacha20poly1305/sodium \
build/libsodium/libsodium/src/libsodium/crypto_auth \
build/libsodium/libsodium/src/libsodium/crypto_auth/hmacsha256 \
build/libsodium/libsodium/src/libsodium/crypto_auth/hmacsha512 \
build/libsodium/libsodium/src/libsodium/crypto_auth/hmacsha512256 \
build/libsodium/libsodium/src/libsodium/crypto_box \
build/libsodium/libsodium/src/libsodium/crypto_box/curve25519xsalsa20poly1305 \
build/libsodium/libsodium/src/libsodium/crypto_core/curve25519/ref10 \
build/libsodium/libsodium/src/libsodium/crypto_core/hchacha20 \
build/libsodium/libsodium/src/libsodium/crypto_core/hsalsa20 \
build/libsodium/libsodium/src/libsodium/crypto_core/hsalsa20/ref2 \
build/libsodium/libsodium/src/libsodium/crypto_core/salsa/ref \
build/libsodium/libsodium/src/libsodium/crypto_generichash/blake2b \
build/libsodium/libsodium/src/libsodium/crypto_generichash/blake2b/ref \
build/libsodium/libsodium/src/libsodium/crypto_generichash \
build/libsodium/libsodium/src/libsodium/crypto_hash \
build/libsodium/libsodium/src/libsodium/crypto_hash/sha256/cp \
build/libsodium/libsodium/src/libsodium/crypto_hash/sha256 \
build/libsodium/libsodium/src/libsodium/crypto_hash/sha512/cp \
build/libsodium/libsodium/src/libsodium/crypto_hash/sha512 \
build/libsodium/libsodium/src/libsodium/crypto_kdf/blake2b \
build/libsodium/libsodium/src/libsodium/crypto_kdf \
build/libsodium/libsodium/src/libsodium/crypto_kx \
build/libsodium/libsodium/src/libsodium/crypto_onetimeauth \
build/libsodium/libsodium/src/libsodium/crypto_onetimeauth/poly1305/donna \
build/libsodium/libsodium/src/libsodium/crypto_onetimeauth/poly1305 \
build/libsodium/libsodium/src/libsodium/crypto_pwhash/argon2 \
build/libsodium/libsodium/src/libsodium/crypto_pwhash \
build/libsodium/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256 \
build/libsodium/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/nosse \
build/libsodium/libsodium/src/libsodium/crypto_scalarmult \
build/libsodium/libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10 \
build/libsodium/libsodium/src/libsodium/crypto_scalarmult/curve25519 \
build/libsodium/libsodium/src/libsodium/crypto_secretbox \
build/libsodium/libsodium/src/libsodium/crypto_secretbox/xsalsa20poly1305 \
build/libsodium/libsodium/src/libsodium/crypto_shorthash \
build/libsodium/libsodium/src/libsodium/crypto_shorthash/siphash24/ref \
build/libsodium/libsodium/src/libsodium/crypto_shorthash/siphash24 \
build/libsodium/libsodium/src/libsodium/crypto_sign \
build/libsodium/libsodium/src/libsodium/crypto_sign/ed25519/ref10 \
build/libsodium/libsodium/src/libsodium/crypto_sign/ed25519 \
build/libsodium/libsodium/src/libsodium/crypto_stream/chacha20/ref \
build/libsodium/libsodium/src/libsodium/crypto_stream/chacha20 \
build/libsodium/libsodium/src/libsodium/crypto_stream \
build/libsodium/libsodium/src/libsodium/crypto_stream/salsa20/ref \
build/libsodium/libsodium/src/libsodium/crypto_stream/salsa20 \
build/libsodium/libsodium/src/libsodium/crypto_stream/xsalsa20 \
build/libsodium/libsodium/src/libsodium/crypto_verify/sodium \
build/libsodium/libsodium/src/libsodium/randombytes \
build/libsodium/libsodium/src/libsodium/sodium \
build/libsodium/port \
build/log \
build/lwip/apps/dhcpserver \
build/lwip/apps/ping \
build/lwip/apps/sntp \
build/lwip/lwip/src/api \
build/lwip/lwip/src/apps/netbiosns \
build/lwip/lwip/src/apps/sntp \
build/lwip/lwip/src/core \
build/lwip/lwip/src/core/ipv4 \
build/lwip/lwip/src/core/ipv6 \
build/lwip/lwip/src/netif \
build/lwip/port/esp32/debug \
build/lwip/port/esp32/freertos \
build/lwip/port/esp32/netif \
build/lwip/port/esp32 \
build/main \
build/mbedtls/mbedtls/library \
build/mbedtls/port/esp32 \
build/mbedtls/port \
build/mdns \
build/mqtt/esp-mqtt/lib \
build/mqtt/esp-mqtt \
build/newlib \
build/nghttp/nghttp2/lib \
build/nghttp/port \
build/nvs_flash/src \
build/openssl/library \
build/openssl/platform \
build/perfmon \
build/protobuf-c/protobuf-c/protobuf-c \
build/protocomm/proto-c \
build/protocomm/src/common \
build/protocomm/src/security \
build/protocomm/src/simple_ble \
build/protocomm/src/transports \
build/pthread \
build/sdmmc \
build/soc/esp32 \
build/soc/src/hal \
build/soc/src \
build/spi_flash \
build/spi_flash/esp32 \
build/spiffs \
build/spiffs/spiffs/src \
build/tcp_transport \
build/tcpip_adapter \
build/ulp \
build/unity/unity/src \
build/unity \
build/vfs \
build/wear_levelling \
build/wifi_provisioning/proto-c \
build/wifi_provisioning/src \
build/wpa_supplicant/port \
build/wpa_supplicant/src/ap \
build/wpa_supplicant/src/common \
build/wpa_supplicant/src/crypto \
build/wpa_supplicant/src/eap_peer \
build/wpa_supplicant/src/esp_supplicant \
build/wpa_supplicant/src/rsn_supp \
build/wpa_supplicant/src/tls \
build/wpa_supplicant/src/utils \
build/wpa_supplicant/src/wps \
build/xtensa \
main \

